### PR TITLE
Stage One CI Integration step implemented along with CLI command to i…

### PR DESCRIPTION
**Pull request by jbcurtin**
…nstall Stage-One into repos

This PR is the first of many PRs to build a CI solution around automating and managing CI for multiple notebook repositories. Currently `spacetelescope`: `jdat_notebooks`, `notebooks`, and `dat_pyinthesky` utilize the CI Pipeline software for Circle-CI that can be installed automatically with the `install` sub-command

Consolidated commit messages,
```
Added documentation and uninstall command
Added GithubIntegration to manage creating and delete github-repos for testing
Implemented GithubIntegration as a pytest.fixture
nbcollection_tests integrations Github and Local is stable
CircleCi local tests implemented
Added command venv to manage different virtual-envs. This'll come in handy to improve communication for debugging notebook builds
Updated Documentation for venv command
Added template-files for nbcollection-ci venv command
Added more details to venv
Added GitPython to setup.cfg
```

Following the command style of `nbcollection`, `nbcollection-ci` is introduced to perform a few different operations

Installing or Uinstalling CircleCI into a repo,
```
Install
nbcollection-ci install --ci-type circle-ci --repo-path git@github.com:jbcurtin/nbcollection-notebook-test-repo.git
nbcollection-ci install --ci-type circle-ci --repo-path https://github.com/jbcurtin/nbcollection-notebook-test-repo
nbcollection-ci install --ci-type circle-ci --repo-path /tmp/local-repo

Uninstall
nbcollection-ci uninstall --ci-type circle-ci --repo-path ...
```
Partial test coverage has been included with ☝️ 
Partial documentation has been included with ☝️ 

Generating the notebook directory,
```
nbcollection-ci venv --env-type virtualenv -d /tmp/new-notebook
```
Not much test coverage has been included with ☝️ 
Partial documentation has been included with ☝️ 

`venv` sub-command is a wrapper around managing different virtual environment types. Currently `virtualenv` is implemented. `Python VENV`, `Conda`, and `Mini-Conda` are all planed to be implemented

### CODE REVIEW

**Comment by adrn** [comment]
Hi @jbcurtin - very sorry for the delay on this (I have been dealing with a family emergency and have had limited time). I will take a close look at this early next week! One quick comment: It looks like there are notebooks included here that might not belong in this repo - can you clarify? thanks!

**Comment by eteq** [comment]
@jbcurtin - as you might have noticed above, we tagged a few other people on the Astropy Learn team to look through this.  But some of them have less of the context here than you, me, and @adrn.  Can you leave a comment here with a bit more of the context about the bigger picture here?  I.e., what we discussed an an out-of-band conversation last week about how this machinery can be adapted to other CI systems, etc?


Additionally, can you try to split the "test repo" part of this into a separate commit?  That will make it a bit easier to split out what's the "result" and what's the "generator". (Also we probably don't want all of those notebooks in this repo in the long-term - just one or two examples.  But that's not critical right now if you can just split it into two commits.)

**Comment by jbcurtin** [comment]
ah, great. Thank you @eteq !

Welcome and please allow me to explain my understanding and plans. When Adrian(@adrn ), Erik(@eteq ), and I first met. We had three questions to focus on first. Here they are and the associated answers that go along with them in History.

### History
#### Understand how to do the “branding”/repo-specific customization

To expand on this, we want to build into the Build Machinery, the capability for Reviewers to brand their notebooks. As to how to configure this, I'm imagining creating a configuration file. Which aligns with commonly implemented open-source project structures. Rendering a notebook with a particular branding can be an automated task that is executed by build machinery on the initial commit after the build machinery is installed. This allows us to write tutorials and other documents to help teams get up to speed quickly on how to use the build machinery and gain experience on how to use it. My goal is to have this software so well polished, that it'll naturally increase the confidence level of the user within days of self-study

We agreed that the HTML, CSS, and JS should come from a template directory. As we had discussed this in the meeting, currently, there isn't an implementation of this. Before adrn and I were brought together, I took a shot at doing this with Github Actions. Here is an example,

Website: https://jbcurtin.io/
Template Folder: https://github.com/jbcurtin/jbcurtin.io/tree/master/template

The build machinery in my personal repository works with Github Actions, while this Pull Request year reading here is using CircleCI. The notebook directory structure for this PR to render notebooks needs to follow this directory structure
https://github.com/astropy/nbcollection#converting-a-directory-structure-of-specific-notebook-files


#### Agree where to put the shared machinery?

We decided first `adrn` and now the `astropy` Github Organization

#### "one notebook per folder" or not (https://github.com/adrn/nbstatic/issues/1)?

Having one notebook per folder may make things cleaner for some, others would find this tedious. We settled on allowing multiple notebooks to exist in the same folder. The compromise comes with files used to build the notebooks

In order to build a notebook. We might add a `pre_install.sh` to install unique requirements to the specific notebook. Such as [`webbpsf` data](https://github.com/spacetelescope/jdat_notebooks/blob/master/notebooks/psf_photometry/pre-install.sh#L6). There is also a [`requirements.txt` file](https://github.com/spacetelescope/jdat_notebooks/blob/master/notebooks/psf_photometry/requirements.txt) to install dependencies. These files will be used to create the environment used to render the notebook

### Problem We're trying to Solve

We're trying to build software for the Scientific Review process, if we were The Washington Post, this could be the Editorial Pipeline for the News Desk. My goal with this software is to automate as many of the code-manual steps as possible so that Scientists and Technical Reviewers don't spend time aligning their `conda`, `virutal-env`, `python-venv`, and other environments. Instead, they spend their hours doing science or writing about science

After discussing with Erik, the Review Process loops on the following steps
* Science Review
* Technical Review
* Notebook Lead takes feedback and integrates it

At the minimum, this could be three persons. One if that one person is super ambitious. My goal is to template the human experience between these three persons using `nbcollection-ci`. To make it as seamless as possible. Erik or somebody else, should be able to say, "Replicate the notebook locally and test this using `nbcollection-ci replicate`". Taking less than 30 minutes to learn assuming the individual has an understanding of Python and Pip/Conda beforehand. Afterwards becoming super intuitive to repeat to the point where it may feel almost effortless

### nbcollection-ci Design Plan

After our meeting, I decided to separate the build machinery into a second command so that I wouldn't disrupt Adrian's efforts with the HTML rendering. Creating `nbcollection-ci`, matching the coding style Adrian had started the repository with. It became evidently clear that there are a lot of moving parts and in turn, I had decided to test every single moving part with integration tests using `pytest`. This is one of the reasons why `nbcollection-notebook-test-repo` exists. Its static data that can be installed into a fresh github repository with recently installed build machinery

Eating our own dog food in tests, a github repo is generated with a temporary name. Build Machinery installed, then the notebooks are installed and tested. `nbcollection-notebook-test-repo` provides an iterative collection of issues build machinery will come across and have to have the correct response to out in the wild

#### nbcollection-ci replicate

The `replicate` command, initial requirement is to capture a Pull Request from a Github Repository and create an environment for the user locally

#### nbcollection-ci venv

`venv` wraps `conda`, `virtualenv`, `python-venv`, and `spm` to provide a uniform interface. Reducing the learning time for all involved so that they only have to learn how to use `nbcollection-ci venv`

#### nbcollection-ci install

`install` installs build machinery into a local directory, Github Repository, or other types of git systems

#### nbcollection-ci uninstall

`uninstall` does the opposite of `install` for all the same targets

### nbcollection-monitor Design Plan

I haven't discussed this with anyone, some thoughts in the back of my mind about how to monitor different repositories. Following the concepts of mesh-networking, we'd monitor different repositories and curated data-collection to identify notebooks that are being rendered without build machinery into similar groups. We can group these repos into a list similar to the (`ABC is awesome` github repos)[https://github.com/vuejs/awesome-vue]

**Comment by jbcurtin** [comment]
RE: @eteq 
```
Additionally, can you try to split the "test repo" part of this into a separate commit? That will make it a bit easier to split out what's the "result" and what's the "generator". (Also we probably don't want all of those notebooks in this repo in the long-term - just one or two examples. But that's not critical right now if you can just split it into two commits.)
```

Yeah, splitting this out is in the plan. I haven't had a chance to get to that stage yet!

**Comment by adrn** [comment]
Thanks @jbcurtin for the explanation above! Any chance you would be able to split up the commits?

**Comment by jbcurtin** [comment]
hey @adrn , yeah. I've opened https://github.com/astropy/nbcollection/pull/10, expanding to three commits

**Pull request closed without merging**
