### PR TITLE
A more comprehensive pull request

### PR DESCRIPTION
**Pull request by jbcurtin**
This pull request is being written in a way that'll provide a comprehensive overview of whats been completed in `nbcollection.ci` module. Covering both the `nbcollection_tests` and `nbcollection/ci` folder, code structure, and interface design. 

Due to the unique nature of this implementation, integrations have been implemented in the testing framework to quickly setup, run, and destroy tests on a local filesystem or Github Repository generated through the Github API. Which will not be covered in this Pull Request. This pull request will only generate file-system based repositories.

### Testing implementation in this Pull Request

For concurrent builds, regenerating CI/CD Build Machinery will remain a first class feature for the foreseeable future. It'll also be how Build Machinery is installed in repositories. 

```
$ pip install git+https://github.com/jbcurtin/nbcollection.git
$ git clone git@github.com:spacetelescope/jdat_notebooks.git /tmp/jdat_notebooks
$ nbcollection-ci generate-ci-env -c jdat_notebooks -p /tmp/jdat_notebooks
$ cd /tmp/jdat_notebooks
$ git diff
$ git commit -m 'Regenerated Notebook Build Machinery' -a
$ git push origin main
```

### CI/CD for nbcollection & nbcollection-ci

In the future, we'll need to write integrations for CircleCI and Github to generate projects and repositories for specific case testing inside the CircleCI CI/CD process. Needless to say, CI/CD with this repository will become complex and organizing code which runs the CI/CD requires a simple, yet power interface.

`tox.ini` was imported from https://github.com/spacetelescope/corazon along with the Github Workflows. `tox.ini` was than adapted to meet specific implementation details for this repository.

#### Supported Python versions

* Python 3.6
* Python 3.7
* Python 3.8
* Python 3.9

#### Operating System support

* Ubuntu LTS 20.04
* Red Hat Enterprise Linux [ Currently tested using generic Linux operating system ]
* macOS Catalina 10.15
* Windows Server 2019

#### Utility Support

* Bandit Security Audit
* Flake8 PEP-8
* Sphinx Link Checking
* Code Cov ( not yet configured )

#### Links to files with implementation
* https://github.com/astropy/nbcollection/blob/24be362cefb1993fcbdfd83aeba18ca691a722ce/.github/workflows/ci_workflows.yml
* https://github.com/astropy/nbcollection/blob/24be362cefb1993fcbdfd83aeba18ca691a722ce/.gitignore
* https://github.com/astropy/nbcollection/blob/24be362cefb1993fcbdfd83aeba18ca691a722ce/Makefile
* https://github.com/astropy/nbcollection/blob/24be362cefb1993fcbdfd83aeba18ca691a722ce/ci_requirements.txt
* https://github.com/astropy/nbcollection/blob/24be362cefb1993fcbdfd83aeba18ca691a722ce/.bandit.yaml
* https://github.com/astropy/nbcollection/blob/24be362cefb1993fcbdfd83aeba18ca691a722ce/.github/workflows/ci_cron_weekly.yml

#### Notebook Collection

A notebook collection is a collection of categories, or folders just relative to the root-level of a Repository.

#### Notebook Category

A notebook category is a folder of notebooks relative or deeply nested inside a notebook collection. There can be many categories per collection. Notebook Categories are transformed into isolated build environments and notebooks within are ordered and executed sequentially.

### Code Structure

Included in `nbcollection_tests` are complete Jupyter Notebooks matching edge cases found inside `spacetelescope/jdat_notebooks` and `spacetelescope/dat_pyinthesky` repositories. The testing notebooks only implement a minimum amount of code required to cause a failed test if `nbcollection.ci` code isn't implemented correctly. With each notebook, a specific test-case is created in `nbcollections_tests`. Most of the tests can be found in `nbcollection_tests/test_scanner.py` file as that is where most of the Jupyter Notebook processing is implemented.

#### Scanner Module

`nbcollection.ci.scanner` implements most file-system operations for locating, collecting, mutating, and altering files. At the core of its design is isolated environment creation for each Notebook Category rendered by `.scanner`. Using Python Generators, `nbcollection.ci.datatypes.JobContext` are generated and can later be iterated over for the notebooks within to be built.

##### Commandline Interface
```
$ nbcollection-ci build-notebooks --collection-names jdat_notebooks --project-path /tmp/dat_pyinthesky
```

##### Python API
```
from nbcollection.ci.scanner.utils import find_build_jobs, generate_job_context, run_job_context

project_path = '/tmp/dat_pyinthesky'
collection_names = ['jdat_notebooks']

for job_idx, job in enumerate(find_build_jobs(project_path, collection_names)):

    # Construct an isolated build environment by generating the job context
    job_context = generate_job_context(job)

    # Execute Jupyter Notebooks by running the Job Context
    run_job_context(job_context)
```

#### Metadata Module

`nbcollection.ci.metadata` implements functions to extract useful information from Jupyter Notebooks. Today, we can extract the Jupyter Notebook title and description from the first cell. Once I seen an example of DevNotes, extracting them at build time will be possible too.

###### Extract Metadata
```
nbcollection-ci metadata --mode extract-metadata --collection-names jdat_notebooks --project-path /tmp/dat_pyinthesky --category-name asdf_example
```

###### Reset Notebook Cell Execution
```
nbcollection-ci metadata --mode reset-notebooks --collection-names jdat_notebooks --project-path /tmp/dat_pyinthesky --category-name asdf_example
```
###### Extract Metadata
```
from nbcollection.ci.scanner.utils import find_build_jobs, generate_job_context
from nbcollection.ci.metadata.utils import extract_metadata

project_path = '/tmp/dat_pyinthesky'
collection_names = ['jdat_notebooks']
category_names = ['asdf_example']

for job in find_build_job(project_path, collection_names, category_names):
    job_context = generate_job_context(job)
    for notebook_context in job_context.notebooks:
        metadata = extract_metadata(notebook_context)
```
###### Reset Notebook Cell Execution
```
import json

from nbcollection.ci.scanner.utils import find_build_jobs, generate_job_context
from nbcollection.ci.metadata.utils import reset_notebook_execution

project_path = '/tmp/dat_pyinthesky'
collection_names = ['jdat_notebooks']
category_names = ['asdf_example']

for job in find_build_job(project_path, collection_names, category_names):
    job_context = generate_job_context(job)
    for notebook_context in job_context.notebooks:
        with open(notebook_context.path, 'rb') as stream:
            notebook_data = json.loads(stream.read().decode(ENCODING))

        reset_notebook_execution(notebook_data)

        with open(notebook_context.path, 'wb') as stream:
            stream.write(json.dumps(notebook_data).encode(ENCODING))
```

#### Generate CI Environment Module

With the `.scanner` module doing most of the heavy work, building notebooks. `.generate_ci_environment` provides the CI/CD logic to be installed into Github Repositories. In order to implement concurrent builds, `.circleci/config.yaml` will need to be regenerated on every merge into `main`. Which works out well when it comes to maintaining consistency with installing the program into a repository. All the user has to do is checkout a repo, and point the generate command towards it.

##### Commandline Interface
```
$ nbcollection-ci generate-ci-env --collection-names jdat_notebooks --ci-environment circle-ci --project-path /tmp/dat_pyinthesky
```
##### Python Interface
```
from nbcollection.ci.commands.datatypes import CIEnvironment
from nbcollection.ci.generate_ci_environment.utils import gen_ci_env

project_path = '/tmp/dat_pyinthesky'
collection_names = ['jdat_notebooks']
jobs = []

for job in find_build_jobs(project_path, collection_names):
    jobs.append(job)

gen_ci_env(jobs, CIEnvironment.CircleCI, project_path)
```
#### Merge Artifacts Module
After a few CI/CD runs, artifacts are generated and presented in CircleCI from `nbcollection-ci build-notebooks` command. In the event you'd like to publish these artifacts to a website, specifically to Github Pages. This command will do that for you. If you'd like to automate publication, that'll be implemented in `nbcollection-ci generate-ci-env` in the near future. Until then, here are the manual steps to complete Website Publication by merging artifacts found in CircleCI.

##### Commandline Interface
```
$ nbcollection-ci merge-artifacts --org spacetelescope --repo-name dat_pyinthesky
```

##### Python Interface
```
from nbcollection.ci.merge_artifacts.utils import artifact_merge

project_path = '/tmp/dat_pyinthesky'
repo_name = 'dat_pyinthesky'
org = 'spacetelescope'
collection_names = ['jdat_notebooks']

artifact_merge(project_path, repo_name, org, collection_names)
```

### CODE REVIEW

**Comment by eteq** [comment]
I noticed you closed #12, @jbcurtin - is that subsumed by this PR?

**Comment by stargaser** [comment]
I am trying this out on some repositories, most recently https://github.com/stargaser/astrometry_prior 

- In the generated `.circleci/config.yml`, I had to change `CI_PULL_REQUEST` to `CIRCLE_PULL_REQUEST`, looks like it is deprecated?
- In the packages to install, `pip install GitPython requests toml PyYaml bs4 jinja2 nbformat nbconvert lxml ` I found it necessary to add `virtualenv`.
- I had some confusion about how the machinery works, initially, as I already had a conda environment for my repo and I thought I had to install `nbcollection` into it. Now I understand, I can just use a setup for `nbcollection`, and it will use virtualenv and the `requirements.txt` to install what is needed for each notebook.
- I find that I must push my notebooks down two levels in order to make the `nbcollection-ci` functions work, at least `build-notebooks` for rendering. I see now that this is explained as, the first folder is a "collection" and the second level is a "category". It would be helpful to state up at the top, more succinctly, what the requirements are on a repository.
- Related to that point, I would like to set up continuous integration for https://github.com/NASA-NAVO/navo-workshop but all our notebooks are in the top level. I am uncertain what to do in that case.

**Comment by jbcurtin** [comment]
> I noticed you closed #12, @jbcurtin - is that subsumed by this PR?

Yeah, #12 was closed because the documentation has been resubmitted in this PR.

**Comment by jbcurtin** [comment]
hey @stargaser , thank you for your feedback.
> In the generated .circleci/config.yml, I had to change CI_PULL_REQUEST to CIRCLE_PULL_REQUEST, looks like it is deprecated?

The latest on `main` has been updated to use `CIRCLE_PULL_REQUEST`

> In the packages to install, pip install GitPython requests toml PyYaml bs4 jinja2 nbformat nbconvert lxml I found it necessary to add virtualenv.

The latest on `main` has been updated to use Python's `venv` module. Installing `virtualenv` shouldn't be necessary anymore.

I'd like to think over the next three items for a bit.

**Pull request closed without merging**
